package JAVA_1_MEMO_JDK_GC;
// ================================================================================
// JAVA MEMORY & JVM — STRUCTURED, DETAILED, BULLET-POINT EXPLANATION (ONE WINDOW)
// ================================================================================

// JVM ARCHITECTURE
// --------------------------------------------------------------------------------
// • The Java Virtual Machine (JVM) is the runtime engine that executes Java bytecode
//   and enables platform independence by abstracting the underlying OS and hardware.
// • The JVM is responsible for loading classes, verifying bytecode, managing memory,
//   executing instructions, handling threads, and running garbage collection.
// • Java source code is compiled into platform-independent bytecode, which the JVM
//   interprets or compiles into native machine code at runtime.

// JDK vs JRE vs JVM
// --------------------------------------------------------------------------------
// • The Java Development Kit (JDK) is used for development and includes the Java
//   compiler, debugging tools, monitoring utilities, and a complete JRE.
// • The Java Runtime Environment (JRE) is used only for running applications and
//   contains the JVM along with core Java libraries.
// • The JVM is the core component that actually executes bytecode and manages memory.
// • Developers install the JDK, while production systems typically require only JRE.

// CLASSLOADER SUBSYSTEM
// --------------------------------------------------------------------------------
// • The ClassLoader subsystem dynamically loads Java classes into memory when they
//   are first referenced, instead of loading all classes at startup.
// • The Bootstrap ClassLoader loads core Java classes such as java.lang.Object and
//   is implemented in native code, making it trusted by the JVM.
// • The Extension ClassLoader loads platform extension libraries that enhance the
//   core Java API but are not part of the standard library.
// • The Application ClassLoader loads user-defined classes from the classpath and
//   handles almost all application-level code.
// • The parent-delegation model ensures security by preventing applications from
//   overriding core Java classes.

// HEAP MEMORY
// --------------------------------------------------------------------------------
// • Heap memory is a shared runtime area where all Java objects and instance variables
//   are stored and accessed by all application threads.
// • The heap is divided into generations to optimize garbage collection based on
//   object lifetime characteristics.
// • The Young Generation stores newly created objects and consists of Eden and two
//   Survivor spaces.
// • Objects are first allocated in Eden space because most objects are short-lived.
// • Objects that survive a Minor Garbage Collection are moved to Survivor spaces.
// • Objects that survive multiple Minor GCs are promoted to the Old Generation.
// • The Old Generation stores long-lived objects such as caches and session data.

// STACK MEMORY
// --------------------------------------------------------------------------------
// • Stack memory is thread-private and each thread has its own stack.
// • The stack stores method call frames, local variables, primitive values, and
//   object references.
// • Each method invocation creates a new stack frame that is removed once the
//   method completes execution.
// • Stack memory is managed automatically and is not controlled by garbage collection.
// • Stack operations are fast because memory allocation and deallocation follow
//   a strict LIFO (Last In First Out) order.

// METASPACE
// --------------------------------------------------------------------------------
// • Metaspace stores class metadata including class structure, method definitions,
//   field information, and constant pool data.
// • Metaspace is allocated in native memory instead of heap memory.
// • Unlike PermGen, Metaspace can grow dynamically until it reaches system limits.
// • Excessive class loading or ClassLoader leaks can cause Metaspace OutOfMemoryError.

// CODE CACHE
// --------------------------------------------------------------------------------
// • Code Cache stores native machine code generated by the Just-In-Time (JIT) compiler.
// • Frequently executed bytecode (hot code) is compiled into native instructions to
//   improve execution performance.
// • If the Code Cache becomes full, the JVM may disable further JIT compilation,
//   causing performance degradation.

// GARBAGE COLLECTION
// --------------------------------------------------------------------------------
// • Garbage Collection is an automatic process that identifies and removes objects
//   that are no longer reachable by the application.
// • The JVM determines object liveness using reachability analysis starting from
//   GC Roots such as stack references and static variables.
// • Minor GC cleans the Young Generation and occurs frequently.
// • Major or Full GC cleans the Old Generation and is more expensive.

// GC ALGORITHMS
// --------------------------------------------------------------------------------
// • The Mark phase identifies all objects that are still reachable.
// • The Sweep phase removes unreachable objects from memory.
// • The Compact phase rearranges objects to eliminate memory fragmentation.
// • Young Generation GC typically uses a copying algorithm.
// • Old Generation GC uses mark-sweep-compact algorithms.

// GC TYPES
// --------------------------------------------------------------------------------
// • Serial GC uses a single thread for garbage collection and is suitable for small
//   applications.
// • Parallel GC uses multiple GC threads to improve throughput.
// • CMS GC minimizes pause times but can cause fragmentation and is deprecated.
// • G1 GC divides the heap into regions and provides predictable pause times.
// • ZGC and Shenandoah perform most GC work concurrently to achieve ultra-low latency.

// STOP-THE-WORLD (STW)
// --------------------------------------------------------------------------------
// • Stop-The-World is a JVM event during which all application threads are paused.
// • Threads are not placed in WAITING or BLOCKED states but are frozen by the JVM.
// • STW ensures memory consistency while the Garbage Collector performs critical work.
// • Minor and Major garbage collections both involve STW pauses.
// • Modern GC algorithms aim to minimize the duration of STW pauses.

// MEMORY LEAKS
// --------------------------------------------------------------------------------
// • A memory leak occurs when objects are no longer needed but are still referenced.
// • Common causes include static collections, unclosed resources, and listener leaks.
// • Memory leaks cause increasing heap usage and frequent garbage collection cycles.
// • Prolonged memory leaks eventually result in OutOfMemoryError.

// OUTOFMEMORYERROR
// --------------------------------------------------------------------------------
// • OutOfMemoryError occurs when the JVM cannot allocate required memory.
// • Heap space errors occur due to excessive object creation or memory leaks.
// • Metaspace errors occur due to excessive class loading.
// • GC overhead errors occur when the JVM spends most of its time performing GC.

// STACKOVERFLOWERROR
// --------------------------------------------------------------------------------
// • StackOverflowError occurs when stack memory exceeds its allocated limit.
// • The most common cause is infinite or excessively deep recursion.
// • Unlike OutOfMemoryError, StackOverflowError is related to stack memory only.

// FINAL REAL-WORLD SUMMARY
// --------------------------------------------------------------------------------
// • Heap stores objects and is managed by garbage collection.
// • Stack stores execution context and is thread-private.
// • Metaspace stores class metadata and grows dynamically.
// • Code Cache improves performance through JIT compilation.
// • GC reclaims unused memory automatically.
// • STW pauses threads briefly to ensure safe memory management.

// ================================================================================
// END — JVM MEMORY EXPLAINED CLEARLY, STRUCTURED, AND INTERVIEW-READY
// ================================================================================




/*
================================================================================
🔥 JAVA EXECUTION, JDK / JRE / JVM, MEMORY, GC — MASTER CHEAT-SHEET (ONE WINDOW)
Author  : Shivam
Purpose : End-to-End Java understanding (Execution → Memory → GC → Internals)
Use     : Interview prep + real-world mental model
================================================================================

────────────────────────────────────────────────────────────────────────────────
1️⃣ WHAT HAPPENS WHEN YOU RUN A JAVA PROGRAM (COMPLETE FLOW)
────────────────────────────────────────────────────────────────────────────────

Source Code
-----------
Shivam.java
    │
    │ javac (Compiler – part of JDK/bin)
    ▼
Shivam.class
→ BYTECODE (Platform Independent)

Execution
---------
java Shivam
    │
    ▼
JVM Process Starts (OS-level process)
    │
    ├─ ClassLoader Subsystem
    │   ├─ Bootstrap  → loads java.base (Object, String, System)
    │   ├─ Platform   → loads standard Java libs
    │   └─ App        → loads user classes (Shivam.class)
    │
    ├─ Bytecode Verifier
    │   ├─ Stack safety check
    │   ├─ Access control
    │   └─ Prevents memory corruption
    │
    ├─ Execution Engine
    │   ├─ Interpreter → executes bytecode line-by-line
    │   └─ JIT Compiler → hot code → native machine code
    │
    ▼
CPU executes native instructions
    ▼
Program Output

👉 Key Idea:
• Bytecode is portable
• JVM is platform dependent
• Performance improves over time due to JIT

────────────────────────────────────────────────────────────────────────────────
2️⃣ JDK / JRE / JVM — CLEAR DIFFERENCE
────────────────────────────────────────────────────────────────────────────────

JDK (Java Development Kit)
• Used for DEVELOPMENT
• Contains:
  - javac (compiler)
  - java (launcher)
  - jar, javadoc, jdb, jshell
  - jmods (runtime modules)
  - JVM (libjvm)

JRE (Java Runtime Environment)
• Used for RUNNING applications
• Contains:
  - JVM
  - Core libraries (java.lang, java.util, java.io…)

JVM (Java Virtual Machine)
• Used for EXECUTION
• Responsibilities:
  - Load classes
  - Verify bytecode
  - Manage memory
  - Run GC
  - Execute bytecode

👉 Relation:
JDK = JRE + Dev Tools
JRE = JVM + Runtime Libraries

/*

────────────────────────────────────────────────────────────────────────────────
3️⃣ JVM INTERNAL ARCHITECTURE + MEMORY + OS + CPU (WHAT RUNS WHERE & WHEN)
────────────────────────────────────────────────────────────────────────────────

JVM PROCESS (Runs as OS Process)
│ // JVM itself is an OS-level process
│ // OS allocates RAM + CPU time to JVM
│
├── Class Loader Subsystem
│   │ // Uses OS RAM (via JVM)
│   │
│   ├─ Bootstrap ClassLoader
│   │   // Loads core Java classes (Object, String) example: java.base → java.lang, java.util, java.io
│   │   // Implemented in native code (C/C++)
│   │   // Classes metadata stored in Metaspace (RAM)
│   │
│   ├─ Platform ClassLoader
│   │   // Loads standard Java libraries  java.sql, java.xml, java.logging
│   │   // Metadata stored in Metaspace (RAM) 
│   │
│   └─ Application ClassLoader
│       // Loads user classes from classpath / JAR - EX:  User defined classes
│       // Metadata stored in Metaspace (RAM)
│
├── Runtime Data Areas (ALL CREATED IN RAM)
│   │
│   ├─ Stack (Per Thread)
│   │   // Allocated in OS RAM
│   │   // One Stack per Thread
│   │   // Created when thread starts
│   │   // Stores method frames
│   │   // Frame contains:
│   │   // - Local primitive variables (values)
│   │   // - References to Heap objects
│   │   // Destroyed when method returns
│   │   // NOT managed by GC
│   │
│   ├─ Heap (Shared Across Threads)
│   │   // Allocated in OS RAM
│   │   // Managed by JVM + GC
│   │   // Stores actual OBJECTS & ARRAYS
│   │   // Divided into Young & Old Gen
│   │   // GC frees memory here
│   │
│   ├─ Metaspace (Native Memory)
│   │   // Allocated from OS RAM (outside Heap)
│   │   // Stores:
│   │   // - Class metadata
│   │   // - Static variables
│   │   // - Method info
│   │   // Freed when ClassLoader unloads classes
│   │
│   ├─ PC Register (Per Thread)
│   │   // NOT in Heap or Stack
│   │   // Logical register (CPU-related)
│   │   // Stores address of current bytecode instruction
│   │   // Used during:
│   │   // - Context switching
│   │   // - Multithreading
│   │   // Updated EVERY instruction execution
│   │
│   └─ Native Method Stack
│       // Allocated in OS RAM
│       // Used when Java calls native (C/C++) code
│       // Works with JNI
│
├── Execution Engine
│   │ // Uses CPU directly
│   │
│   ├─ Interpreter
│   │   // Reads bytecode from memory
│   │   // Executes instruction-by-instruction
│   │   // Uses CPU for execution
│   │
│   ├─ JIT Compiler
│   │   // Runs inside JVM
│   │   // Compiles hot bytecode → native machine code
│   │   // Stores compiled code in Code Cache (RAM)
│   │
│   └─ Garbage Collector
│       // Runs on CPU threads
│       // Scans Heap in RAM
│       // Frees unreachable objects
│       // Stop-the-world or concurrent (GC dependent)
│
├── Code Cache (Native Memory)
│   │ // Allocated in OS RAM
│   │ // Stores JIT-compiled native code
│   │ // CPU executes directly from here
│
└── JNI (Java Native Interface)
    // Bridge between Java & native code
    // Allows JVM to call OS / C / C++ libraries
    // Uses Native Method Stack + CPU



Who manages what in JVM memory

| Memory Area                  | Managed By                       | Lives Where            | Notes                                                                                                 |
| ---------------------------- | -------------------------------- | ---------------------- | ----------------------------------------------------------------------------------------------------- |
| **Heap**                     | **JVM (Garbage Collector)**      | OS RAM                 | Stores all objects & arrays, GC frees unreachable objects, divided into Young + Old Gen               |
| **Stack (per thread)**       | **JVM**                          | OS RAM                 | Stores method frames, local primitives, references; auto-cleared when method returns; NOT GC-managed  |
| **Metaspace**                | **JVM (via ClassLoader unload)** | OS RAM (native memory) | Stores class metadata, static variables, method info; freed only when ClassLoader becomes unreachable |
| **Code Cache**               | **JVM**                          | OS RAM (native)        | Stores JIT-compiled native code; CPU executes directly                                                |
| **PC Register (per thread)** | **JVM + CPU**                    | CPU register           | Tracks current bytecode instruction; updated on each execution                                        |
| **Native Method Stack**      | **JVM**                          | OS RAM                 | Used for native method calls (C/C++ via JNI)                                                          |


🔑 Key Points

All JVM memory areas are managed by JVM, not the OS directly.

OS provides raw RAM, JVM divides it into Heap, Stack, Metaspace, Code Cache, etc.

Heap → GC cleans

Stack → Auto-cleared when methods return

Metaspace → Cleared when ClassLoader unloads

Code Cache → Managed by JVM for JIT-compiled code

PC Register → Used by CPU + JVM to track execution


────────────────────────────────────────────────────────────────────────────────
OS / RAM / CPU RELATIONSHIP (CRITICAL INTERVIEW POINTS)
────────────────────────────────────────────────────────────────────────────────

• JVM = OS Process
• OS provides RAM → JVM divides it into Heap, Stack, Metaspace
• CPU executes:
  - Interpreted bytecode
  - JIT compiled native code
• PC Register tracks current instruction per thread
• GC threads also consume CPU
• Heap & Metaspace live in RAM
• Stack lives in RAM (per thread)
• Code Cache lives in RAM
• Nothing runs without CPU
• Nothing stores without RAM



────────────────────────────────────────────────────────────────────────────────
4️⃣ JVM MEMORY ARCHITECTURE (DIAGRAM WITH INLINE COMMENTS ONLY)
────────────────────────────────────────────────────────────────────────────────

┌────────────────────────────────────────────────────────────┐
│ Metaspace (Native Memory – NOT Heap)                       │
│------------------------------------------------------------│
│ • Stores CLASS-LEVEL data                                  │
│ • Class metadata (name, methods, fields)                   │
│ • Static variables                                         │
│ • Method bytecode structure                                │
│                                                            │
│ Who manages it?                                            │
│ • JVM (NOT Garbage Collector)                              │
│                                                            │
│ How memory is freed?                                       │
│ • When ClassLoader unloads classes                         │
│ • Uses OS native memory                                    │
│                                                            │
│ Notes                                                      │
│ • Replaced PermGen (Java 8+)                               │
│ • Can grow dynamically        //Before java 8 in 6-7 - it was fixed size                             │
└────────────────────────────────────────────────────────────┘
                ▲
                │ ClassLoader loads classes & metadata
                │
┌────────────────────────────────────────────────────────────┐
│ Heap Memory (GC Managed – Shared)                          │
│------------------------------------------------------------│
│ • Stores ALL objects & arrays                              │
│ • Shared across all threads                                │
│                                                            │
│ Who manages it?                                            │
│ • Garbage Collector (G1 / ZGC / etc.)                      │
│                                                            │
│ How allocation works?                                      │
│ • Objects created via `new` go here                        │
│                                                            │
│  Young Generation                                         │
│  ----------------                                         │
│  ├─ Eden Space                                             │
│  │   • New objects allocated                               │
│  │   • Cleaned by Minor GC                                 │
│  │                                                        │
│  ├─ Survivor S0 / S1                                      │
│  │   • Objects that survived Minor GC                     │
│  │   • Objects age here                                   │
│                                                            │
│  Old / Tenured Generation                                  │
│  -----------------------                                  │
│  • Long-lived objects                                      │
│  • Cleaned by Major / Full GC                              │
│                                                            │
│  String Pool (inside Heap)                                 │
│  ---------------------------                               │
│  • Stores interned String literals                         │
│  • Only one copy per literal                               │
│                                                            │
│ How memory is freed?                                       │
│ • GC removes unreachable objects                           │
└────────────────────────────────────────────────────────────┘
                ▲
                │ Stack holds references to Heap objects
                │
┌────────────────────────────────────────────────────────────┐
│ Stack Memory (Per Thread – NOT GC Managed)                 │
│------------------------------------------------------------│
│ • Each thread has its OWN stack                            │
│                                                            │
│ Who manages it?                                            │
│ • JVM automatically                                       │
│                                                            │
│ What lives here?                                           │
│ • Method call frames                                       │
│ • Local primitive variables                                │
│ • References to Heap objects                               │
│                                                            │
│ How memory is freed?                                       │
│ • When method returns                                     │
│ • When thread terminates                                   │
│                                                            │
│ Errors                                                     │
│ • StackOverflowError → deep recursion                      │
└────────────────────────────────────────────────────────────┘

┌────────────────────────────────────────────────────────────┐
│ Code Cache (Native Memory)                                 │
│------------------------------------------------------------│
│ • Stores JIT compiled native machine code                  │
│                                                            │
│ Who manages it?                                            │
│ • JVM JIT Compiler                                         │
│                                                            │
│ How it works?                                              │
│ • Hot bytecode → compiled → stored here                   │
│ • CPU executes directly                                   │
│                                                            │
│ Why needed?                                                │
│ • Improves performance over time                           │
└────────────────────────────────────────────────────────────┘


👉 Facts:
• Heap → shared across threads
• Stack → per thread
• GC works ONLY on Heap

/*
================================================================================
OBJECT CREATION + GARBAGE COLLECTION (GC) FLOW — COMPLETE LOGIC VIEW
Author : Shivam
Purpose: Understand HOW objects are created, WHERE they go, WHEN GC runs,
         WHO decides, and HOW memory is finally freed (INTERVIEW + REAL WORLD)
================================================================================
*/

/*
================================================================================
1️⃣ OBJECT CREATION — STEP BY STEP
================================================================================
*/
/*
new Object()
│
// JVM Execution Engine receives bytecode instruction: new
│
├─► Check Thread Local Allocation Buffer (TLAB)
│     // Small private Eden area per thread
│
│     if (TLAB has enough space)
│         → allocate object in Eden via TLAB (FAST, no lock)
│
│     else
│         → check Eden free space
│
├─► Eden Space (Young Generation, Heap)
│     // FIRST allocation area for almost all objects
│     // Managed by JVM Garbage Collector
│
│     if (Eden has enough contiguous space)
│         → allocate object in Eden
│
│     else
│         → trigger Minor GC
│
▼
Object created successfully
// Reference stored in Stack frame of the thread
// Object itself lives in Heap (Eden)

// /*
// ================================================================================
// 2️⃣ MINOR GC — WHEN & WHY
// ================================================================================
// */

// Trigger Condition:
// ------------------
// Eden Space FULL → Minor GC (mandatory)

// Who triggers:
// -------------
// JVM Garbage Collector (Execution Engine)

// Why Minor GC:
// -------------
// • Eden fills very fast (short-lived objects)
// • Free space for new allocations

// /*
// ================================================================================
// 3️⃣ MINOR GC — INTERNAL LOGIC
// ================================================================================
// */

// Minor GC Process:
// -----------------
// 1. Identify GC Roots
//    • Stack references (local variables)
//    • Static fields (from Metaspace)
//    • CPU registers (PC Register)
//    • JNI references

// 2. Reachability Analysis
//    • Reachable objects → ALIVE
//    • Unreachable objects → DEAD

// 3. Object Movement
//    • DEAD objects in Eden → REMOVED (memory freed)
//    • ALIVE objects →
//          Eden → Survivor Space (S0 or S1)
//          object.age++

// 4. Eden is completely cleared

// // Stop-The-World (very short pause)

// /*
// ================================================================================
// 4️⃣ SURVIVOR SPACE (S0 / S1) — AGE & FLIP LOGIC
// ================================================================================
// */

// // Survivor Rules:
// // ---------------
// // • Two survivor spaces: S0 and S1
// // • Only ONE survivor space active at a time

// // After each Minor GC:
// // --------------------
// // Eden + Active Survivor → Empty Survivor

// // Object Age:
// // -----------
// // • Each object carries an age counter
// // • Age increments after every Minor GC

// /*
// ================================================================================
// 5️⃣ PROMOTION TO OLD GENERATION — DECISION LOGIC
// ================================================================================
// */

// An object is promoted to Old Generation if:

// Rule 1:
// -------
// object.age >= MaxTenuringThreshold (default ≈ 15)

// Rule 2:
// -------
// Survivor Space is FULL

// Rule 3:
// -------
// Object is very large (bypasses Survivor)

// Result:
// -------
// Object copied into Old / Tenured Generation
// // Old Gen is GC’d less frequently

// /*
// ================================================================================
// 6️⃣ MAJOR / FULL GC — WHEN & HOW
// ================================================================================
// */

// Trigger Conditions:
// ------------------
// • Old Generation almost FULL
// • Promotion failure
// • Explicit System.gc() (hint only)

// Major GC Process:
// -----------------
// • Full Heap scan (Young + Old)
// • Identify unreachable objects
// • Remove dead objects from Old Gen
// • Optional memory compaction

// // Stop-The-World (long pause)

// /*
// ================================================================================
// 7️⃣ MEMORY FREEING — IMPORTANT TRUTH
// ================================================================================
// */

// • GC frees memory ONLY in Heap
// • Stack memory auto-cleared on method return
// • Metaspace cleared when ClassLoader unloaded
// • Code Cache cleared by JVM internally

// /*
// ================================================================================
// 8️⃣ WHY THIS DESIGN WORKS (CORE IDEA)
// ================================================================================
// */

// • 90% objects die young → cheap Minor GC
// • Long-lived objects moved to Old Gen
// • Less frequent expensive GC on Old Gen
// • High throughput + optimized memory use

// /*
// ================================================================================
// 9️⃣ COMPLETE FLOW — ONE LOOK
// ================================================================================
// */

// new Object()
//    ↓
// TLAB → Eden
//    ↓
// Eden full?
//    ↓ YES
// Minor GC
//    ├─ unreachable → delete
//    └─ reachable → Survivor (age++)
//           ↓
// Age threshold / Survivor full?
//           ↓ YES
//         Old Gen
//           ↓
// Old Gen full?
//           ↓ YES
//        Major GC

// /*
// ================================================================================
// 🔟 INTERVIEW ONE-LINER
// ================================================================================
// */

// "Objects are first allocated in Eden. When Eden fills, Minor GC runs and live
// objects are moved to Survivor spaces. Objects surviving multiple Minor GCs or
// unable to fit in Survivor spaces are promoted to Old Generation, where Major GC
// runs less frequently to reclaim long-lived objects."

// /*
// ================================================================================
// END — OBJECT CREATION & GC FLOW CHEAT-SHEET
// ================================================================================


// ────────────────────────────────────────────────────────────────────────────────
// 6️⃣ STRING MEMORY EXPLAINED
// ────────────────────────────────────────────────────────────────────────────────

// String a = "java";
// • Stored in String Pool (Heap)

// String b = new String("java");
// • New object in Heap (NOT pooled)

// b.intern();
// • Returns reference from String Pool

// Only STRING literals are pooled
// Primitives are NOT pooled

// Boxed primitives:
// Integer.valueOf(-128 to 127) → cached

// ────────────────────────────────────────────────────────────────────────────────
// 7️⃣ MEMORY LEAK vs OUT OF MEMORY
// ────────────────────────────────────────────────────────────────────────────────

// Memory Leak Example:
// List<String> list = new ArrayList<>();
// while(true) {
//     list.add("leak");
// }

// • Objects still referenced
// • GC cannot free
// • Heap fills
// • Eventually → OutOfMemoryError

// Memory Leak = Cause
// OOM Error    = Result

// ────────────────────────────────────────────────────────────────────────────────
// 8️⃣ GARBAGE COLLECTION TYPES
// ────────────────────────────────────────────────────────────────────────────────

// Minor GC
// • Cleans Young Generation
// • Fast & frequent

// Major / Full GC
// • Cleans Old Generation
// • Slow, Stop-The-World

// GC Implementations
// • Serial GC      → small apps
// • Parallel GC    → throughput-oriented
// • G1 GC          → balanced (DEFAULT)
// • ZGC            → ultra-low latency
// • Shenandoah     → concurrent low pause
// • CMS            → deprecated

// System.gc()
// • Only a REQUEST
// • JVM may ignore

// ────────────────────────────────────────────────────────────────────────────────
// 9️⃣ IMPORTANT JVM FLAGS (COMMON)
// ────────────────────────────────────────────────────────────────────────────────

// -Xms       → Initial heap size
// -Xmx       → Max heap size
// -XX:+UseG1GC
// -XX:+UseZGC
// -XX:MaxMetaspaceSize
// -XX:+PrintGCDetails

// ────────────────────────────────────────────────────────────────────────────────
// 🔟 ONE-LINE EXECUTION SUMMARY (INTERVIEW GOLD)
// ────────────────────────────────────────────────────────────────────────────────

// .java
//  → javac
//  → .class (bytecode)
//  → java
//  → JVM
//  → ClassLoader
//  → Verifier
//  → Interpreter + JIT
//  → Heap / Stack / Metaspace
//  → GC
//  → CPU
//  → Output

// ────────────────────────────────────────────────────────────────────────────────
// 🔥 GOLDEN INTERVIEW FACTS (RAPID FIRE)
// ────────────────────────────────────────────────────────────────────────────────

// • JDK = JRE + Dev Tools
// • JRE = JVM + Libraries
// • JVM is platform dependent
// • Bytecode is platform independent
// • GC manages only Heap
// • Stack is per-thread
// • String Pool is inside Heap
// • Metaspace uses native memory
// • JIT improves performance over time
// • Memory leak ≠ OOM
// • Objects die only when unreachable

// ================================================================================
// ✅ END — COMPLETE JAVA CHEAT-SHEET IN ONE CODE WINDOW
// ================================================================================
// */
